[phases.install]
cmds = [
  "cd sme-finhealth-backend && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd sme-finhealth-backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
